name: june_vm_module
description: "help june package to manage state in juneflow project"
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/june_vm_module

version: 1.0.5

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.2
  june_flow_util: ^0.8.19
  june: ^0.8.8 #@add

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/module/june_vm_module/
  uses-material-design: true